### ISSUE TITLE
unsigned int pHex = TFT_GREEN; // Paul = cyan

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [paulmartinetti/twatch-take8#1]
Hello paul i have tried your code and i get this error.

`C:\Users\jJcSystems\Documents\Arduino\libraries\twatch-take8-main\displayTime\displayTime.ino: In function 'void displayTime(boolean)':
displayTime:16:23: error: 'TFT_GREEN' was not declared in this scope
   unsigned int pHex = TFT_GREEN; // Paul = cyan
                       ^
displayTime:24:3: error: 'RTC_Date' was not declared in this scope
   RTC_Date tnow = watch->rtc->getDateTime();
   ^
displayTime:26:3: error: 'hh' was not declared in this scope
   hh = tnow.hour;
   ^
displayTime:26:8: error: 'tnow' was not declared in this scope
   hh = tnow.hour;
        ^
displayTime:27:3: error: 'mm' was not declared in this scope
   mm = tnow.minute;
   ^
displayTime:28:3: error: 'ss' was not declared in this scope
   ss = tnow.second;
   ^
displayTime:29:3: error: 'dday' was not declared in this scope
   dday = tnow.day;
   ^
displayTime:30:3: error: 'mmonth' was not declared in this scope
   mmonth = tnow.month;
   ^
displayTime:31:3: error: 'yyear' was not declared in this scope
   yyear = tnow.year;
   ^
displayTime:33:3: error: 'tft' was not declared in this scope
   tft->setTextSize(1); // normal size. 2 is double
   ^
displayTime:40:21: error: 'TFT_BLACK' was not declared in this scope
     tft->fillScreen(TFT_BLACK);
                     ^
displayTime:58:13: error: 'power' was not declared in this scope
   int pct = power->getBattPercentage();
             ^
C:\Users\jJcSystems\Documents\Arduino\libraries\twatch-take8-main\displayTime\wifiTime.ino: In function 'void appWiFiTime()':
wifiTime:14:14: error: 'ssid' was not declared in this scope
   WiFi.begin(ssid, password);
              ^
wifiTime:14:20: error: 'password' was not declared in this scope
   WiFi.begin(ssid, password);
                    ^
wifiTime:85:15: error: 'oweatherURL' was not declared in this scope
   http2.begin(oweatherURL);
               ^
exit status 1
'TFT_GREEN' was not declared in this scope

`

I have never saw errors like that before.

Joseph

**Comment by paulmartinetti** [comment]
Sorry about that. I just updated config.h with more explanation and variable declarations. Keep me posted. Best wishes.

**Comment by paulmartinetti** [comment]
Also please note that I commented out the region call. If you remove the /**/ it will work.

**Comment by Therealjosephchrzempiec** [comment]
Hello I'm still getting the same errors. I'm not sure what I'm doing wrong. My skills are mostly in hardware designing and building. I can follow dirctions in coding and modding a few things here and there. I'm learning as i go along.


Joseph

**Comment by paulmartinetti** [comment]
Thanks for your patience, I am also new to C++. Please use the new config.h file from this morning. You have to replace 4 variables with your own info as I wrote in the comments. I verified that it will compile as is, but the watch won't work without your local info.

**Comment by Therealjosephchrzempiec** [comment]
Hello i have downloaded all the latest code. I still get the same error. 

![1](https://user-images.githubusercontent.com/50338148/104484344-31de3180-5597-11eb-9ace-6c3b62ca31c4.png)
![2](https://user-images.githubusercontent.com/50338148/104484349-3276c800-5597-11eb-8068-0442a5980c36.png)



Joseph

**Comment by paulmartinetti** [comment]
Joseph, Thank you for including screen shots! Please launch WakeupFromSensor2.ino instead of displayTime.ino. Arduino will ask you to create a copy in a folder with the same name, say yes. Keep me posted. Best wishes, Paul

**Comment by Therealjosephchrzempiec** [comment]
Oh sorry let me redo that. 


Joseph

**Comment by paulmartinetti** [comment]
WakeupFromSensor2.ino has to run in a folder called WakeupFromSensor2 with the 4 files as separate tabs.

**Comment by Therealjosephchrzempiec** [comment]
Hello i finally got it working. I never used tabs before. I open the WakeupFormSensor2 in it's own folder like you said called WakeupFormSensor2 and then i open the Ardino IDE. in there i couldn't see the other files. So i had to search online how to add file as tabs by clicking on the Sketch button at the top of arduino IDE then clicking on Add file and finding where each file is then i was able to add each one as a tab. Thank you.

The only problem is I'm on the road a lot so i don't have wifi access in most places. Is there a way i can manually add the time and date please? The Weather I'm not really needing right now. But the time and date i love to  change manually.


Joseph

**Comment by paulmartinetti** [comment]
I had the same problem with the IDE. Once you make the WakeupFromSensor2 folder, you put the other 3 files in the folder and they should open. I will update my instructions -- thank you.

The watch keeps pretty accurate time without the wifi. I think it starts with the computer's time.

If I code a screen to update time, I'll message you. I'm still learning..

Paul

**Comment by Therealjosephchrzempiec** [comment]
Hello Paul thank you so much. How can i increase the delay before it goes to sleep?


Joseph

**Comment by paulmartinetti** [comment]
As of 13-Jan-21, to increase the wake time, sorry it's a bit complicated:

In WakeupFromSensor2 (30 = 3 seconds)
- line 144, change 30 to, for example 50 or 90
- line 158, change 30 to the same new number

In wifiTime (if you use it)
- line 193 change 31 to your number plus 1..so 51 or 91 for example.

I will make this easier to do as soon as I can. Thank you for your input and interest!

**Comment by Therealjosephchrzempiec** [comment]
Hello Paul, you are awesome thank you very much.
