### ISSUE TITLE
WiFi connecting being stuck

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [paulmartinetti/twatch-take8#2]
Hello Paul, I notice that if I'm not at the location where I setup the WiFi for my phone and I accidentally tap on the screen it try's to connect to WiFi and just sits there on the connection screen. So I have to manually hold the side button into it goes off then told the button again to bring it back. 

Is there a way if it can not connect to WiFi after 5 seconds or something that it can go back to sleep or go back to the time and date clock?

Joseph

**Comment by paulmartinetti** [comment]
Hey Joseph, again sorry for the trouble. The WiFi timeout code that I've tried thus far does not work. I'm working on it and will keep you posted. Thanks again, Paul

**Comment by Therealjosephchrzempiec** [comment]
Thank you Paul. Yeah I notice that but I wasn't sure if it was something I did or what it was.


Joseph

**Comment by paulmartinetti** [comment]
Joseph, I found a function that closes WiFi on fail. It works for me. Give it a try and keep me posted. Best, Paul

**Comment by Therealjosephchrzempiec** [comment]
Testing new code now. Will report back when away from my wifi.


Joseph

**Comment by Therealjosephchrzempiec** [comment]
Hey Paul just A heads up. How long would it take to search for the WiFi before it timed out and goes back to sleep? I put the new code on and it keep still saying connecting and sitting there.


Joseph

**Comment by paulmartinetti** [comment]
Please make sure you have the new wifiConnect file from today, that's where the new function is. It's a built-in function from the included Wifi library and it doesn't let me specify the wait time. When I put my ssid="", pw="" it timed out after about 10 seconds.

**Comment by Therealjosephchrzempiec** [comment]
I will have to check it again when I get home. I did download the newest files, All of them.


Joseph

**Comment by paulmartinetti** [comment]
If it doesn't work for you, in the main file , you can comment out // line 163, which calls the wifiConnect() function and it should just stay on the clock screen and go to sleep.

**Comment by Therealjosephchrzempiec** [comment]
Hello Paul the failure part works. I didn't put my WiFi in. So today I'm adding the WiFi said and password then I will test it. Sorry I couldn't get back to you yesterday I fell a sleep.


Joseph

**Comment by paulmartinetti** [comment]
Hello Joseph, thanks for the update and keep me posted on the WiFi. Have a good one, Paul
