### ISSUE TITLE
New sleep time?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [paulmartinetti/twatch-take8#3]
Hey Paul sorry i have been busy with health problems But i was wondering Where the New sleep is at how to change it to stay awake alittle longer?

Joseph

**Comment by paulmartinetti** [comment]
Hey Joseph,
Glad you're feeling better.
In the file WakeupFromSensor2, line 41 you can increase this to 50 or 70 to keep it awake longer. 
It's about 10 times the number of seconds that you want it to stay awake.
Best wishes,
Paul
